# Generated by Django 4.2.5 on 2023-10-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='reply',
            name='rank',
            field=models.IntegerField(max_length=10),
        ),
    ]
